apiVersion: v1
kind: Secret
metadata:
  name: thanos-object-storage
  namespace: open-cluster-management-observability
type: Opaque
stringData:
  thanos.yaml: |
    type: AZURE
    config:
      storage_account: bW9uaXRvcmluZ2Fyb3JnM2Ns
      storage_account_key: KytkM3d0U1FXQmZ5Ym0vanNPU20rS3lDcGdEeGlWc1AzZ0F1Qk9GdlhKdzNqQzdlZHZUUFlpL2FJZGN4UHZvQ1k0VkN1YXNJQUR2NCtBU3RoTDA2Rnc9PQ
      container: acm-observability
      endpoint: blob.core.windows.net 
      max_retries: 0