apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: minio
  name: minio-server
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: minio
  template:
    metadata:
      labels:
        app.kubernetes.io/name: minio
    spec:
      containers:
        - name: minio
          env:
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-access-secrets
                  key: minioAccessKey
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-access-secrets
                  key: minioSecret
            - name: MINIO_CONSOLE_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: minio-access-secrets
                  key: minioConsoleAddress
          image: minio/minio
          args:
            - server
            - /data
          ports:
            - containerPort: 9000
              protocol: TCP
              name: web
          volumeMounts:
            - name: home
              mountPath: /data
            - name: config
              mountPath: /root/.minio
      volumes:
        - name: home
          persistentVolumeClaim:
            claimName: minio-home-claim
        - name: config
          persistentVolumeClaim:
            claimName: minio-config-claim