apiVersion: v1
kind: Secret
type: Opaque
metadata:
  annotations: {}
  name: minio-access-secrets
stringData:
  minioSecret: ${MINIO_ADMIN_PWD}
  minioAccessKey: minio
  minioConsoleAddress: ":44645"
