apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-virtualization
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/fmendonca/openshift.git
    targetRevision: HEAD
    path: argocd/virtualization
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
