apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-virtualization
  namespace: openshift-cnv
spec:
  channel: stable
  name: openshift-virtualization
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic
